# Generated by Django 4.0.4 on 2022-05-20 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, null=True, upload_to='uploads/images', verbose_name='Фото')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='Email')),
                ('address', models.TextField(max_length=400, verbose_name='Адрес')),
                ('phone', models.CharField(blank=True, max_length=25, null=True, verbose_name='Телефон')),
            ],
        ),
    ]
